import { PrismaClient } from "./generated/prisma/index.js";
// This file is generated by Prisma. Do not edit it manually.
// To regenerate, run `npx prisma generate` in the terminal.

export const prismaClient = new PrismaClient();